language: python
python:
  - "3.7"

services:
  - docker

env:  # N times sandboxes created and built by jobs
  global:
    - IS_LOCAL=false

branches:
  only:
    - master
    - devel

before_install:
  - curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
  - >
    scversion="stable" # or "v0.4.7", or "latest"
    wget -qO- "https://storage.googleapis.com/shellcheck/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv
    cp "shellcheck-${scversion}/shellcheck" /usr/local/bin/
    shellcheck --version

install:
  - make
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make hub

deploy:
  provider: script
  script: make hub
  on:
    repo: jinwoo/influxdb
    tags: true
    
after_failure: docker ps