version: "3"
services:
  influxdb:
    image: jinwoo/influxdb:1.7.9
    container_name: influxdb
    user: influxdb
    ports:
      - "8086:8086"
    restart: on-failure
    environment:
      - INFLUXDB_HTTP_LOG_ENABLED="false"
#      - INFLUXDB_DATA_INDEX_VERSION="tsi1"
    volumes:
      - "/data/influxdb/log:/var/log/influxdb"
#    command: influxd
